=== Andover-Robotics/5273-centerstage/simulation_data/RobotConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Robot" type="RobotType"/>

    <xs:complexType name="RobotType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="motor5202" type="Motor5202Type" minOccurs="4" maxOccurs="4"/>
            <xs:element name="wheel96mm" type="Wheel96mmType" minOccurs="4" maxOccurs="4"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Motor5202Type">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Wheel96mmType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="connection" type="ConnectionType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ConnectionType">
        <xs:sequence>
            <xs:element name="motor" type="xs:string"/>
            <xs:element name="gearRatio" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Andover-Robotics/5273-centerstage/simulation_data/RealRobotConfig.xml
<?xml version="1.0" encoding="utf-8" ?>

<Robot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RobotConfig.xsd">
    <name>drivetrain</name>
    <motor5202>
        <id>driveFrontLeft</id>
        <name>Drive Front Left Motor</name>
    </motor5202>
    <motor5202>
        <id>driveFrontRight</id>
        <name>Drive Front Right Motor</name>
    </motor5202>
    <motor5202>
        <id>driveBackLeft</id>
        <name>Drive Back Left Motor</name>
    </motor5202>
    <motor5202>
        <id>driveBackRight</id>
        <name>Drive Back Right Motor</name>
    </motor5202>
    <wheel96mm>
        <name>Drive Front Left Wheel</name>
        <connection>
            <motor>driveFrontLeft</motor>
            <gearRatio>1</gearRatio>
        </connection>
    </wheel96mm>
    <wheel96mm>
        <name>Drive Front Right Wheel</name>
        <connection>
            <motor>driveFrontRight</motor>
            <gearRatio>1</gearRatio>
        </connection>
    </wheel96mm>
    <wheel96mm>
        <name>Drive Back Left Wheel</name>
        <connection>
            <motor>driveBackLeft</motor>
            <gearRatio>1</gearRatio>
        </connection>
    </wheel96mm>
    <wheel96mm>
        <name>Drive Back Right Wheel</name>
        <connection>
            <motor>driveBackRight</motor>
            <gearRatio>1</gearRatio>
        </connection>
    </wheel96mm>
</Robot>
